---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: nightly


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs daily
  schedule:
    - cron: '0 0 * * *'


jobs:

  # -----------------------------------------------------------------------------------------------
  # Job: BUILD
  # -----------------------------------------------------------------------------------------------
  build:
    name: "[ PHP-${{ matrix.version }} (${{ matrix.arch }}) ] (ref: ${{ matrix.refs }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '8.0'
        arch:
          - 'linux/amd64'
          - 'linux/arm64'
          - 'linux/386'
          - 'linux/arm/v7'
          - 'linux/arm/v6'
        refs:
          - 'master'
          - '0.14'
    steps:

      # ------------------------------------------------------------
      # Setup repository
      # ------------------------------------------------------------
      - name: "[SETUP] Checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ matrix.refs }}

      - name: "[SETUP] Setup QEMU environment"
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: "[SETUP] Determine Docker tag"
        id: tag
        uses: cytopia/docker-tag@v0.3

      # ------------------------------------------------------------
      # Build
      # ------------------------------------------------------------
      - name: Build
        uses: cytopia/shell-command-retry-action@v0.1
        with:
          command: |
            make build ARCH=${ARCH}
        env:
          ARCH: ${{ matrix.arch }}

      # ------------------------------------------------------------
      # Test
      # ------------------------------------------------------------
      - name: "[TEST] Docker Image"
        uses: cytopia/shell-command-retry-action@v0.1
        with:
          command: |
            make test ARCH=${ARCH}
        env:
          ARCH: ${{ matrix.arch }}

      - name: "[TEST] Update README"
        uses: cytopia/shell-command-retry-action@v0.1
        with:
          command: |
            make update-readme ARCH=${ARCH}
        env:
          ARCH: ${{ matrix.arch }}

      - name: "[TEST] Verify README"
        run: |
          git diff --quiet || { echo "Build Changes"; git diff; git status; false; }

      # ------------------------------------------------------------
      # Deploy
      # ------------------------------------------------------------
      - name: "[DEPLOY] Login"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "[DEPLOY] Publish architecture image (only repo owner)"
        uses: cytopia/shell-command-retry-action@v0.1
        with:
          command: |
            make push-arch TAG=${{ steps.tag.outputs.docker-tag }} ARCH=${ARCH}
        env:
          ARCH: ${{ matrix.arch }}
        # https://help.github.com/en/github/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#functions
        if: github.event.pull_request.base.repo.id == github.event.pull_request.head.repo.id
            && (
              (github.event_name == 'schedule' && (github.ref == 'refs/heads/master'   || startsWith(github.ref, 'refs/tags/')))
              ||
              (github.event_name == 'push'     && (github.ref == 'refs/heads/master'   || startsWith(github.ref, 'refs/tags/')))
              ||
              (github.event_name == 'push'     && startsWith(github.ref, 'refs/heads/release-'))
            )

  # -----------------------------------------------------------------------------------------------
  # Job (2/2): DEPLOY
  # -----------------------------------------------------------------------------------------------
  deploy:
    needs: [build]
    name: "[ Deploy (ref: ${{ matrix.refs }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '8.0'
        refs:
          - 'master'
          - '0.14'
    steps:

      # ------------------------------------------------------------
      # Setup repository
      # ------------------------------------------------------------
      - name: "[SETUP] Checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ matrix.refs }}

      - name: "[SETUP] Determine Docker tag"
        id: tag
        uses: cytopia/docker-tag@v0.3

      # ------------------------------------------------------------
      # Deploy
      # ------------------------------------------------------------
      - name: "[DEPLOY] Login"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "[DEPLOY] Create Docker manifest"
        uses: cytopia/shell-command-retry-action@v0.1
        with:
          command: |
            make manifest-create TAG=${{ steps.tag.outputs.docker-tag }} ARCH="linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6"

      - name: "[DEPLOY] Publish Docker manifest (only repo owner)"
        uses: cytopia/shell-command-retry-action@v0.1
        with:
          command: |
            make manifest-push TAG=${{ steps.tag.outputs.docker-tag }}
        # https://help.github.com/en/github/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#functions
        if: github.event.pull_request.base.repo.id == github.event.pull_request.head.repo.id
            && (
              (github.event_name == 'schedule' && (github.ref == 'refs/heads/master'   || startsWith(github.ref, 'refs/tags/')))
              ||
              (github.event_name == 'push'     && (github.ref == 'refs/heads/master'   || startsWith(github.ref, 'refs/tags/')))
              ||
              (github.event_name == 'push'     && startsWith(github.ref, 'refs/heads/release-'))
            )
